### PR TITLE
mdoc: Failing to load an assembly is no longer a fatal error.

### LINKED ISSUE #7: [mdoc] Error when running on a folder with some assemblies being non-managed
For example, if you run:

```
mdoc update *.dll -o folder_name
```
And within the folder (current context) there are DLLs that are native, the tool will fail with:

```
Format of the executable (.exe) or library (.dll) is invalid
```

### PR DESCRIPTION
**Pull request by joelmartinez**
In some cases, for example when running in "frameworks" mode (ie. https://github.com/mono/api-doc-tools/pull/18), you might have non-managed .dlls in the directory. This change allows mdoc to simply write the fact that it couldn't load the assembly, and continue doing work.
Resolves #7
Provices a temporary workaround for #8, #9

### CODE REVIEW

File: mdoc/Mono.Documentation/monodocer.cs [hunk 1]
```diff
@@ -408,10 +411,10 @@ private AssemblyDefinition LoadAssembly (string name)
 		AssemblyDefinition assembly = null;
 		try {
 			assembly = AssemblyDefinition.ReadAssembly (name, new ReaderParameters { AssemblyResolver = assemblyResolver });
-		} catch (System.IO.FileNotFoundException) { }
-
-		if (assembly == null)
-			throw new InvalidOperationException("Assembly " + name + " not found.");
+		} 
+		catch (Exception ex) {
+			Warning ($"Error loading assembly '{name}': {ex.Message}");
```
Comment (jonpryor) [inline mdoc/Mono.Documentation/monodocer.cs]: If it's a *warning*, then you shouldn't say "Error"; that can make things confusing. I would suggest:

    Warning ($"Unable to load assembly `{name}`: {ex.Message}");
