### PR TITLE
mdoc: importer can now handle xml comments.

### LINKED ISSUE #97: [mdoc] Preserving remarks created post-factum on import
One of the issues that we are running when we are importing documentation from docXML is that any remarks that were created in the post-production ECMAXML are erased in favor of the imported ones. Here is the scenario.

1. We onboard a new set of DLLs and import Roslyn-generated docXMLs, giving us a new batch of ECMAXML files.
2. Writers edit the ECMAXML remarks to add code examples.
3. A new version of a packages comes out, so we re-run the `mdoc` to import the new information.
4. The import will overwrite the remarks already in ECMAXMLs in favor of those that are in the files already.

This issue was brought up by @mmacy with the Azure Storage libraries, that rely heavily on remarks and user-created samples.

### LINKED ISSUE #159: [mdoc] Reflection issue over PSCore assemblies
When I am trying to run `mdoc` 5.3 over a number of PSCore assemblies, I get an error:

```
2017-11-12T20:41:21.5552704Z New Type: Microsoft.PowerShell.Commands.GetRandomCommand
2017-11-12T20:41:21.6490438Z ##[error]mdoc: System.Xml.XPath.XPathException: Expression must evaluate to a node-set.
   at MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(AstNode qyInput, AxisType axisType, XPathNodeType nodeType)
   at MS.Internal.Xml.XPath.XPathParser.ParseStep(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseRelativeLocationPath(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseLocationPath(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParsePathExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseUnionExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseUnaryExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseMultiplicativeExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseAdditiveExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseAndExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseOrExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseExpresion(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseXPathExpresion(String xpathExpresion)
   at System.Xml.XPath.XPathExpression.Compile(String xpath, IXmlNamespaceResolver nsResolver)
   at System.Xml.XPath.XPathNavigator.Select(String xpath)
   at System.Xml.XmlNode.SelectNodes(String xpath)
   at Mono.Documentation.Updater.MsxdocDocumentationImporter.ImportDocumentation(DocsNodeInfo info)
   at Mono.Documentation.MDocUpdater.MakeDocNode(DocsNodeInfo info, IEnumerable`1 setimporters)
   at Mono.Documentation.MDocUpdater.UpdateType(XmlElement root, TypeDefinition type, FrameworkTypeEntry typeEntry)
   at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince)
   at Mono.Documentation.MDocUpdater.StubType(TypeDefinition type, String output, IEnumerable`1 importers)
   at Mono.Documentation.MDocUpdater.DoUpdateType(TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblySet assemblySet, AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

### PR DESCRIPTION
**Pull request by joelmartinez**
Bump to v5.3.1. Closes #159 and Closes #97.

### CODE REVIEW

File: mdoc/Mono.Documentation/Updater/MsxdocDocumentationImporter.cs [hunk 1]
```diff
@@ -125,14 +125,18 @@ public override void ImportDocumentation (DocsNodeInfo info)
                         }
                     default:
                         {
-                            bool add = true;
-                            if (child.NodeType == XmlNodeType.Element &&
-                                e.SelectNodes (child.Name).Cast<XmlElement> ().Any (n => n.OuterXml == child.OuterXml))
-                                add = false;
-                            if (add)
+                            var targetNodes = e.ChildNodes.Cast<XmlNode> ()
```
Comment (joelmartinez) [inline mdoc/Mono.Documentation/Updater/MsxdocDocumentationImporter.cs]: @conceptdev or @lobrien ... was wondering if I could get a quick codereview on this logic change. I think what I've written is equivalent, and should have better performance, since it limits the calls to `.OuterXml` (which is [not a free call](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Dom/XmlNode.cs#L952)) to only nodes who's name matches, and also "caches" the `.OuterXml` call of the node being considered for addition.

It passed the local test case for #159, and also passes the CI test suite ... just want a second opinion :)
