### PR TITLE
Fix Recursion for C# Formatter for ValueTuple

### LINKED ISSUE #11939: Return type of ValueTuple.Create with 8 arguments is rendered incorrectly
### Type of issue

Other (describe below)

### Description

At <https://learn.microsoft.com/en-us/dotnet/api/system.valuetuple.create?view=net-9.0#system-valuetuple-create-8(-0-1-2-3-4-5-6-7)>, the method signature is rendered as:

```csharp
public static(T1, T2, T3, T4, T5, T6, T7,(T8)) Create<T1,T2,T3,T4,T5,T6,T7,T8>(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5, T6 item6, T7 item7, T8 item8);
```

The return type should not have parentheses around `T8`:

```csharp
public static(T1, T2, T3, T4, T5, T6, T7, T8) Create<T1,T2,T3,T4,T5,T6,T7,T8>(T1 item1, T2 item2, T3 item3, T4 item4, T5 item5, T6 item6, T7 item7, T8 item8);
```

According to [C# 7 §8.3.11](https://github.com/dotnet/csharpstandard/blob/standard-v7/standard/types.md#8311-tuple-types), `(T1, T2, T3, T4, T5, T6, T7, T8)` means `ValueTuple<T1, T2, T3, T4, T5, T6, T7, ValueTuple<T8>>`.  This is the actual return type of the eight-parameter ValueTuple.Create method.  In this type, the outer structure is [`ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest>`](https://learn.microsoft.com/dotnet/api/system.valuetuple-8?view=net-9.0), whose `TRest` type parameter requires a tuple type.

`(T1, T2, T3, T4, T5, T6, T7, (T8))` means `ValueTuple<T1, T2, T3, T4, T5, T6, T7, ValueTuple<ValueTuple<T8>>>`.  That is not what ValueTuple.Create returns.

In the following member signatures, C# is wrong, but the others are correct because they use generic type syntax rather than tuple type syntax: <https://github.com/dotnet/dotnet-api-docs/blob/9ba1f1b43dfb2b9bc49eb84a2023b1b1ca0c82df/xml/System/ValueTuple.xml#L953-L959>

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.valuetuple.create?view=net-9.0#system-valuetuple-create-8(-0-1-2-3-4-5-6-7)

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/ValueTuple.xml

### Document Version Independent Id

ba9ac4e4-a738-7a26-4841-113a47f798b8

### Platform Id

32cda35d-8dc0-8c5a-710e-541512f6cd40

### Article author

@dotnet-bot

### PR DESCRIPTION
**Pull request by davidle-ms**
Resolves [#11939](https://github.com/dotnet/dotnet-api-docs/issues/11939).

Summary: 
- Fixed C# Formatter to correctly address System.ValueTuple nested ValueTuple structure, where there are more than 7 required fields, it takes the recursive structure: System.ValueTuple<T1, ..., T7, TRest>
- Added unit test cases to validate this change
- Tested this locally with System.ValueTuple.dll, comparing the generated xmls before and after the change. Change in xml file is as expected.

### CODE REVIEW

**Comment by xmdanni** [comment]
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=2517865

**Comment by davidle-ms** [comment]
@dotnet-policy-service agree company="Microsoft"

**Comment by xmdanni** [comment]
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=2521001

**Comment by huangmin-ms** [comment]
@davidle-ms Could you also add unit tests in FormatterTest to verify the change?

**Comment by xmdanni** [comment]
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=2521293

**Comment by davidle-ms** [comment]
> @davidle-ms Could you also add unit tests in FormatterTest to verify the change?

Added.

File: mdoc/Mono.Documentation/Updater/Formatters/CSharpFullMemberFormatter.cs [hunk 1]
```diff
@@ -146,26 +146,43 @@ protected override StringBuilder AppendSpecialGenericNullableValueTypeName (Stri
...
-                buf.Append ("(");
-                var genArgTypeList = new List<string> ();
+                buf.Append("(");
+                var genArgTypeList = new List<string>();
                 // tuple element names should be traversed before recursion.
                 var genArgNameList = genInst.GenericArguments.Select(arg => context.GetTupleElementName()).ToList();
-                foreach (var item in genInst.GenericArguments)
+                for (int index = 0; index < genInst.GenericArguments.Count; index++)
                 {
+                    var item = genInst.GenericArguments[index];
```
Comment (huangmin-ms) [inline mdoc/Mono.Documentation/Updater/Formatters/CSharpFullMemberFormatter.cs]: The for loop change is unnecessary, right?

Comment (davidle-ms) [reply mdoc/Mono.Documentation/Updater/Formatters/CSharpFullMemberFormatter.cs]: Yep, you're right. Previously changed it as I was going to directly reference the 8th index in the loop, but this was changed to just reference it after the loop. I can revert this.

**Comment by xmdanni** [comment]
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=2521400

File: mdoc/Mono.Documentation/Updater/Formatters/CSharpFullMemberFormatter.cs (hunk 1 above)
Comment (davidle-ms) [reply mdoc/Mono.Documentation/Updater/Formatters/CSharpFullMemberFormatter.cs]: Changed

**Comment by huangmin-ms** [comment]
you can also update the version from 5.9.6 to 5.9.7 in this PR. [Code search results](https://github.com/search?q=repo%3Amono%2Fapi-doc-tools+5.9.6&type=code)

**Comment by xmdanni** [comment]
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=2521424

**Comment by davidle-ms** [comment]
> you can also update the version from 5.9.6 to 5.9.7 in this PR. [Code search results](https://github.com/search?q=repo%3Amono%2Fapi-doc-tools+5.9.6&type=code)

Updated

**Review by huangmin-ms — APPROVED** [review]
